apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: slack-bots
  namespace: slack-bots
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    traefik.ingress.kubernetes.io/router.entrypoints: web,websecure
    traefik.ingress.kubernetes.io/router.tls: "true"
    external-dns.alpha.kubernetes.io/hostname: slackbots.headbangtech.com
spec:
  ingressClassName: traefik
  tls:
    - hosts:
        - slackbots.headbangtech.com
      secretName: slackbots-tls
  rules:
    - host: slackbots.headbangtech.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: slack-bots
                port:
                  number: 3000
